### ISSUE TITLE
Integration URL

### ISSUE THREAD

**Issue by gallowaystorm** [OpsLevel/report-deploy-github-action#1]
I am trying to integrate Github Actions with one of our repositories.  Based off your instructions on the Opslevel Integrations page, I should be using this:

```yaml
uses: opslevel/github-actions@v0.0.1
with:
  integration_url: ${{ secrets.OL_INTEGRATION_URL }}
```
When I use this format, I receive the following error from the action:

Unexpected input(s) 'integration_url', valid inputs are ['entryPoint', 'args', 'integrationId', 'service', 'environment', 'number']

After I got this, I went to your Github page and noticed that the action is supposed to be formatted like this:

```yaml
uses: opslevel/report-deploy-github-actions@v0.0.1
with:
  integration_url: ${{ secrets.OL_INTEGRATION_URL }}
```

When I use that in my github action file, I recieve an error that the action does not exist.  I am not sure if the documentation, code, or my implementation is off.  I am more concerned with the fact that "integration_url" is not a valid input in the first error.

Please advise
